name: Build

on:
  push:
    branches:
      - main
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - '.github/workflows/*.yml'
      - 'gradle/**'
  pull_request:
    branches:
      - main
    paths:
      - '**.kt'
      - '**.kts'
      - 'gradle.properties'
      - '.github/workflows/*.yml'
      - 'gradle/**'
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.run_id }}"
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build application packages
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        runtime: [ linux-x64, win-x64 ]
        include:
          - runtime: linux-x64
            arch: x64
            os: ubuntu-latest
            shell: bash
            build: packageUberJarForCurrentOS packageDeb

          - runtime: win-x64
            arch: x64
            os: windows-latest
            shell: powershell
            build: packageUberJarForCurrentOS packageMsi

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    defaults:
      run:
        shell: ${{ matrix.shell }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          architecture: ${{ matrix.arch }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew ${{ matrix.build }}

      # Upload runner package tar.gz/zip as artifact
      - name: Publish Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: runner-package-${{ matrix.runtime }}
          path: |
            tau/app/build/compose/binaries/main/*
            tau/app/build/compose/jars/*.jar

      # Upload runner errors
      - name: Upload error logs
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: runner-errors-${{ matrix.runtime }}
          path: |
            tau/app/build/compose/logs/